# Generated by Django 4.0.6 on 2024-04-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_likedsongs_playlistsongs_userdata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='email',
        ),
    ]
