# Generated by Django 4.0.6 on 2024-04-14 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_remove_userdata_dob_userdata_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedsongs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
