# Generated by Django 4.0.6 on 2024-04-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_recent_played_time_alter_playlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedsongs',
            name='duration',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlistsongs',
            name='duration',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recent_played',
            name='duration',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
