# Generated by Django 4.0.6 on 2024-04-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_likedsongs_duration_playlistsongs_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedsongs',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
